name: Deploy to Hostgator

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Hostgator
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DESTINATION: ${{ secrets.DESTINATION }}
        run: |
          sudo apt-get install lftp
          lftp -c "
            set ftp:ssl-allow no;
            open -u $USER,$PASSWORD $HOST;
            cd $DESTINATION;
            mirror -R dist .;
            bye"
